{% extends "/base/main.phtml" %}
{% block body %}
<h1>Lista de empleados</h1>
<hr>
<div class="col-md-4 col-md-offset-4">
	<form method="GET" action="/empleados">
		<div class="input-group"> 
			<input name="email" class="form-control" placeholder="Buscar por email"> 
			<span class="input-group-btn"> 
				<button class="btn btn-default" type="submit">Buscar!</button> </span> 
		</div>
	</form>
</div>
<div class="clearfix"></div>
<hr>
<table class="table">
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Position</th>
		<th>Salary</th>
		<th>detalle</th>
	</tr>
	{% for index in listaEmpelados %}
	<tr>
	<td>{{ index.name }}</td>
	<td>{{ index.email }}</td>
	<td>{{ index.position }}</td>
	<td>{{ index.salary }}</td>
	<td><a href="/empleado/detalle/{{ index.id }}">ver detalles</a></td>
	</tr>
	{% endfor %}
</table>
{% endblock %}