{% extends "/base/main.phtml" %}
{% block body %}
<h1>Detalles de empleado</h1>
<hr>
<div class="col-md-4 col-md-offset-4">
	<div class="panel panel-default">
  <div class="panel-heading">Informacion del empleado {{ data.name }}</div>
  <div class="panel-body text-left">
    <dl>
		<dt>Name:</dt>
		<dd>{{ data.name }}</dd>
		<dt>Email:</dt>
		<dd>{{ data.email }}</dd>
		<dt>Phone:</dt>
		<dd>{{ data.phone }}</dd>
		<dt>Address:</dt>
		<dd>{{ data.address }}</dd>
		<dt>Position:</dt>
		<dd>{{ data.position }}</dd>
		<dt>Salary:</dt>
		<dd>{{ data.salary }}</dd>
		<dt>Skills:</dt>
		<dd>{{ skillString }}</dd>
	</dl>
	  <a href="/empleados" class="btn btn-default">< Volver</a>
  </div>
</div>
</div>
<div class="clearfix"></div>
<hr>

{% endblock %}