<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Developer Sac</h1>
        <div>Sistema de gestion de empleados</div>
		<br>
        <a class="btn btn-default" href="/empleados">Lista de empleados</a>
		<hr>
		<a href="/service">Servicio XML</a>
		<hr>
		<a href="/service?min=1000&max=2000">Ejemplo Busqueda entre salarios de 1000 y 2000 dolares</a>
		<hr>
    </body>
</html>
